# Generated by Django 6.1.1 on 2026-10-04 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_order', models.PositiveSmallIntegerField()),
                ('score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['game', 'player_order'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('evaluated', 'Evaluated')], default='pending', max_length=20)),
                ('question_type', models.CharField(choices=[('choice', 'Choice'), ('numeric', 'Numeric')], max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('choice_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='questions.choicequestion')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.game')),
                ('numeric_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='questions.numericquestion')),
            ],
            options={
                'ordering': ['game', 'number'],
            },
        ),
        migrations.CreateModel(
            name='RoundAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.gameplayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.round')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='round_answers', to='questions.answeroption')),
            ],
            options={
                'ordering': ['round', 'player__player_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['waiting', 'in_progress', 'finished', 'cancelled'])), name='game_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='game_finished_after_started'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='gameplayer_unique_user_per_game'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'player_order'), name='gameplayer_unique_order_per_game'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.CheckConstraint(condition=models.Q(('player_order__gte', 1), ('player_order__lte', 3)), name='gameplayer_order_in_range'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('game', 'number'), name='round_unique_number_per_game'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='round_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'open', 'closed', 'evaluated'])), name='round_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('choice_question__isnull', False), ('numeric_question__isnull', True), ('question_type', 'choice')), models.Q(('choice_question__isnull', True), ('numeric_question__isnull', False), ('question_type', 'numeric')), _connector='OR'), name='round_question_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='round_finished_after_started'),
        ),
        migrations.AddConstraint(
            model_name='roundanswer',
            constraint=models.UniqueConstraint(fields=('round', 'player'), name='roundanswer_unique_player_per_round'),
        ),
        migrations.AddConstraint(
            model_name='roundanswer',
            constraint=models.CheckConstraint(condition=models.Q(('selected_option__isnull', True), ('numeric_value__isnull', True), _connector='OR'), name='roundanswer_single_answer_kind'),
        ),
    ]
