# Generated by Django 6.1.1 on 2026-10-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Choice'), ('numeric', 'Numeric')], editable=False, max_length=20),
        ),
    ]
