# Generated by Django 6.1.1 on 2026-10-07 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_round_question_type_not_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'adjacencies',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='games.game')),
                ('neighbors', models.ManyToManyField(blank=True, through='territories.Adjacency', through_fields=('from_territory', 'to_territory'), to='territories.territory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territories', to='games.gameplayer')),
            ],
            options={
                'verbose_name_plural': 'territories',
                'ordering': ['game', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='games.gameplayer')),
                ('territory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='territories.territory')),
            ],
            options={
                'ordering': ['territory__game', 'player__player_order'],
            },
        ),
        migrations.AddField(
            model_name='adjacency',
            name='from_territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='territories.territory'),
        ),
        migrations.AddField(
            model_name='adjacency',
            name='to_territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='territories.territory'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='territory_unique_name_per_game'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(fields=('game', 'slug'), name='territory_unique_slug_per_game'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='territory_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='capital',
            constraint=models.CheckConstraint(condition=models.Q(('health__gte', 0), ('health__lte', 3)), name='capital_health_in_range'),
        ),
        migrations.AddConstraint(
            model_name='adjacency',
            constraint=models.UniqueConstraint(fields=('from_territory', 'to_territory'), name='adjacency_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='adjacency',
            constraint=models.CheckConstraint(condition=models.Q(('from_territory', models.F('to_territory')), _negated=True), name='adjacency_no_self_reference'),
        ),
    ]
